### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by julianpolimeni** [zylin/zpugcc#12]
I try to compile the gcc toolchain on ubuntu 16.04 and get following error.Can you support me plz.

configure: warning: ../zpugcc/toolchain/build/../install: invalid host type
creating cache ./config.cache
checking host system type... Invalid configuration ../zpugcc/toolchain/build/../install': machine ../zpugcc/toolchain/build/../install' not recognized

checking target system type... zpu-unknown-none
checking build system type... Invalid configuration ../zpugcc/toolchain/build/../install': machine ../zpugcc/toolchain/build/../install' not recognized

checking for a BSD compatible install... /usr/bin/install -c
../binutils/configure: 841: test: /home/../..: unexpected operator
../binutils/configure: 26: test: /home/../..: unexpected operator
checking for ../zpugcc/toolchain/build/../install-ar... no
checking for ar... ar
checking for ../zpugcc/toolchain/build/../install-as... no
checking for as... as
checking for ../zpugcc/toolchain/build/../install-dlltool... no
checking for dlltool... dlltool
checking for ../zpugcc/toolchain/build/../install-ld... no
checking for ld... ld
checking for ../zpugcc/toolchain/build/../install-nm... no
checking for nm... nm
checking for ../zpugcc/toolchain/build/../install-ranlib... no
checking for ranlib... ranlib
checking for ../zpugcc/toolchain/build/../install-windres... no
checking for windres... windres
checking for ../zpugcc/toolchain/build/../install-objcopy... no
checking for objcopy... objcopy
checking for ../zpugcc/toolchain/build/../install-objdump... no
checking for objdump... objdump
checking for zpu-elf-ar... no
../binutils/configure: 3540: test: =: unexpected operator
checking for zpu-elf-as... no
../binutils/configure: 3612: test: =: unexpected operator
checking for zpu-elf-dlltool... no
../binutils/configure: 3684: test: =: unexpected operator
checking for zpu-elf-ld... no
../binutils/configure: 3756: test: =: unexpected operator
checking for zpu-elf-nm... no
../binutils/configure: 3828: test: =: unexpected operator
checking for zpu-elf-ranlib... no
../binutils/configure: 3900: test: =: unexpected operator
checking for zpu-elf-windres... no
../binutils/configure: 3972: test: =: unexpected operator
checking whether to enable maintainer-specific portions of Makefiles... no
updating cache ./config.cache
creating ./config.status
creating Makefile
Configuring in libiberty
/bin/sh: 0: Can't open /home/../..
Makefile:20071: fallo en las instrucciones para el objetivo 'configure-libiberty'
make: *** [configure-libiberty] Error 1

**Comment by alvieboy** [comment]
You seem to be passing wrong arguments to the "configure" script. Care to share the full command you are typing ? It's probably a missing dash somewhere.

**Comment by julianpolimeni** [comment]
In fact, I passed incorrect arguments to the "configure" script. Thanks for the quick reply.
